AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MeetingPolice HTTPS via ALB + GitHub pull ready
  FastAPI + Nginx + React frontend stack (t3.small)

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair name for SSH access
    Default: EC2-keypair
  GitRepoURL:
    Type: String
    Description: |
      MeetingPolice GitHub repository URL (e.g. https://github.com/yourname/MeetingPolice.git)
    Default: https://github.com/SiguStyle/MeetingPolice
  UbuntuAmiId:
    Type: AWS::EC2::Image::Id
    Description: Ubuntu Server 22.04 LTS (Jammy) AMI ID (ap-northeast-1)
    Default: ami-0244ef75e95122fd9
  VpcCidrBlock:
    Type: String
    Description: CIDR block for MeetingPolice VPC
    Default: 10.20.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Description: CIDR block for the first public subnet (ALB/NAT)
    Default: 10.20.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Description: CIDR block for the second public subnet (ALB)
    Default: 10.20.2.0/24
  PrivateSubnetCidr:
    Type: String
    Description: CIDR block for the private application subnet (EC2)
    Default: 10.20.11.0/24

Resources:
  MeetingPoliceVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: MeetingPolice-VPC

  MeetingPoliceInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MeetingPolice-IGW

  MeetingPoliceIgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      InternetGatewayId: !Ref MeetingPoliceInternetGateway

  MeetingPolicePublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      CidrBlock: !Ref PublicSubnet1Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: MeetingPolice-Public-A

  MeetingPolicePublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      CidrBlock: !Ref PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: MeetingPolice-Public-B

  MeetingPolicePublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      Tags:
        - Key: Name
          Value: MeetingPolice-Public-RT

  MeetingPolicePublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MeetingPolicePublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MeetingPoliceInternetGateway
    DependsOn: MeetingPoliceIgwAttachment

  MeetingPolicePublicSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MeetingPolicePublicSubnetA
      RouteTableId: !Ref MeetingPolicePublicRouteTable

  MeetingPolicePublicSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MeetingPolicePublicSubnetB
      RouteTableId: !Ref MeetingPolicePublicRouteTable

  MeetingPoliceNatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: MeetingPolice-NAT-EIP

  MeetingPoliceNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt MeetingPoliceNatEip.AllocationId
      SubnetId: !Ref MeetingPolicePublicSubnetA
      Tags:
        - Key: Name
          Value: MeetingPolice-NAT
    DependsOn: MeetingPoliceIgwAttachment

  MeetingPolicePrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      CidrBlock: !Ref PrivateSubnetCidr
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: MeetingPolice-Private-App

  MeetingPolicePrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      Tags:
        - Key: Name
          Value: MeetingPolice-Private-RT

  MeetingPolicePrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MeetingPolicePrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref MeetingPoliceNatGateway

  MeetingPolicePrivateSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MeetingPolicePrivateSubnet
      RouteTableId: !Ref MeetingPolicePrivateRouteTable

  MeetingPoliceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: MeetingPoliceAlbSecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS only from ALB
      VpcId: !Ref MeetingPoliceVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref MeetingPoliceAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref MeetingPoliceAlbSecurityGroup

  MeetingPoliceAlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public access for the Application Load Balancer
      VpcId: !Ref MeetingPoliceVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  MeetingPoliceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonTranscribeFullAccess

  MeetingPoliceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref MeetingPoliceRole]

  MeetingPoliceEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      SubnetId: !Ref MeetingPolicePrivateSubnet
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref MeetingPoliceInstanceProfile
      SecurityGroupIds: [!Ref MeetingPoliceSecurityGroup]
      ImageId: !Ref UbuntuAmiId
      Tags:
        - Key: Name
          Value: MeetingPolice-Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -eux
          PROJECT_ROOT="/home/ubuntu/MeetingPolice"

          # ---- Basic setup ----
          sudo apt update -y
          sudo apt install -y git nginx python3 python3-venv python3-pip curl snapd
          # ---- Install Node.js 20 LTS (supports Vite build) ----
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo snap install amazon-ssm-agent --classic
          sudo systemctl enable --now snap.amazon-ssm-agent.amazon-ssm-agent.service

          # ---- Add 2GB swap ----
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

          # ---- Clone MeetingPolice repository as ubuntu ----
          sudo -u ubuntu git clone ${GitRepoURL} $PROJECT_ROOT || \
            (cd $PROJECT_ROOT && sudo -u ubuntu git pull)
          sudo chown -R ubuntu:ubuntu $PROJECT_ROOT
          sudo -u ubuntu git config --global --add safe.directory /home/ubuntu/MeetingPolice
          cd $PROJECT_ROOT

          # ---- Backend: Python virtual environment & dependencies ----
          cd $PROJECT_ROOT/backend
          python3 -m venv .venv
          source .venv/bin/activate
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install fastapi uvicorn[standard]
          fi

          # ---- Frontend: build session-app (as ubuntu) ----
          sudo -u ubuntu bash -lc "cd $PROJECT_ROOT/frontend/session-app && npm install && npm run build"

          # ---- Frontend: build admin-app (as ubuntu) ----
          sudo -u ubuntu bash -lc "cd $PROJECT_ROOT/frontend/admin-app && npm install && npm run build"

          # ---- Nginx configuration (HTTP only, ALB terminates TLS) ----
          sudo tee /etc/nginx/sites-available/meetingpolice > /dev/null <<'EOF'
          server {
              listen 80;
              server_name _;

              location / {
                  root /home/ubuntu/MeetingPolice/frontend/session-app/dist;
                  try_files $uri /index.html;
              }

              location /admin/ {
                  root /home/ubuntu/MeetingPolice/frontend/admin-app/dist;
                  try_files $uri /index.html;
              }

              location /api/ {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location /ws/ {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
              }
          }
          EOF

          sudo rm -f /etc/nginx/sites-enabled/default || true
          sudo ln -s /etc/nginx/sites-available/meetingpolice /etc/nginx/sites-enabled/
          sudo systemctl restart nginx

          # ---- Persist FastAPI with systemd ----
          cat << 'EOF' | sudo tee /etc/systemd/system/meetingpolice-backend.service
          [Unit]
          Description=MeetingPolice FastAPI backend
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/MeetingPolice/backend
          Environment="PATH=/home/ubuntu/MeetingPolice/.venv/bin"
          ExecStart=/home/ubuntu/MeetingPolice/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl enable meetingpolice-backend
          sudo systemctl start meetingpolice-backend
          sudo chown -R ubuntu:ubuntu $PROJECT_ROOT
          echo "MeetingPolice (t3.small) setup complete."
    Metadata:
      Comment: EC2 sets up FastAPI + Nginx from GitHub (t3.small)

  MeetingPoliceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref MeetingPoliceVPC
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: '200'
      Targets:
        - Id: !Ref MeetingPoliceEC2

  MeetingPoliceALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: meetingpolice-alb
      Scheme: internet-facing
      Subnets:
        - !Ref MeetingPolicePublicSubnetA
        - !Ref MeetingPolicePublicSubnetB
      SecurityGroups:
        - !Ref MeetingPoliceAlbSecurityGroup
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'

  MeetingPoliceHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MeetingPoliceALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

Outputs:
  LoadBalancerDNSName:
    Description: DNS name to access MeetingPolice via the ALB
    Value: !GetAtt MeetingPoliceALB.DNSName
