AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MeetingPolice HTTPS (self-signed) + GitHub pull ready
  FastAPI + Nginx + React frontend stack (t3.small)

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair name for SSH access
    Default: EC2-keypair
  GitRepoURL:
    Type: String
    Description: |
      MeetingPolice GitHub repository URL (e.g. https://github.com/yourname/MeetingPolice.git)
    Default: https://github.com/SiguStyle/MeetingPolice
  UbuntuAmiId:
    Type: AWS::EC2::Image::Id
    Description: Ubuntu Server 22.04 LTS (Jammy) AMI ID (ap-northeast-1)
    Default: ami-0244ef75e95122fd9

Resources:
  MeetingPoliceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  MeetingPoliceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  MeetingPoliceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref MeetingPoliceRole]

  MeetingPoliceEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref MeetingPoliceInstanceProfile
      SecurityGroupIds: [!Ref MeetingPoliceSecurityGroup]
      ImageId: !Ref UbuntuAmiId
      Tags:
        - Key: Name
          Value: MeetingPolice-Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -eux
          PROJECT_ROOT="/home/ubuntu/MeetingPolice"

          # ---- Basic setup ----
          sudo apt update -y
          sudo apt install -y git nginx python3 python3-venv python3-pip nodejs npm curl openssl snapd
          sudo snap install amazon-ssm-agent --classic
          sudo systemctl enable --now snap.amazon-ssm-agent.amazon-ssm-agent.service

          # ---- Add 2GB swap ----
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

          # ---- Clone MeetingPolice repository ----
          git clone ${GitRepoURL} $PROJECT_ROOT || (cd $PROJECT_ROOT && git pull)
          cd $PROJECT_ROOT

          # ---- Auto switch to ubuntu user when SSM login ----
          sudo tee -a /home/ssm-user/.bashrc > /dev/null <<'EOF'
          if [ -z "$MEETINGPOLICE_SSM_SWITCHED" ]; then
              export MEETINGPOLICE_SSM_SWITCHED=1
              exec sudo -iu ubuntu bash -lc 'cd /home/ubuntu/MeetingPolice && exec bash'
          fi
          EOF
          sudo chown ssm-user:ssm-user /home/ssm-user/.bashrc

          # ---- Python virtual environment ----
          python3 -m venv venv
          source venv/bin/activate
          pip install fastapi uvicorn[standard]

          # ---- Generate self-signed SSL certificate ----
          sudo mkdir -p /etc/ssl/meetingpolice
          sudo openssl req -x509 -nodes -days 825 -newkey rsa:2048 \
            -subj "/C=JP/ST=Tokyo/L=Tokyo/O=MeetingPolice/CN=localhost" \
            -keyout /etc/ssl/meetingpolice/server.key \
            -out /etc/ssl/meetingpolice/server.crt

          # ---- Nginx configuration ----
          sudo tee /etc/nginx/sites-available/meetingpolice > /dev/null <<'EOF'
          server {
              listen 80;
              server_name _;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name _;

              ssl_certificate /etc/ssl/meetingpolice/server.crt;
              ssl_certificate_key /etc/ssl/meetingpolice/server.key;

              location / {
                  root /home/ubuntu/MeetingPolice/frontend/session-app/dist;
                  try_files $uri /index.html;
              }

              location /admin/ {
                  root /home/ubuntu/MeetingPolice/frontend/admin-app/dist;
                  try_files $uri /index.html;
              }

              location /api/ {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location /ws/ {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
              }
          }
          EOF

          sudo ln -s /etc/nginx/sites-available/meetingpolice /etc/nginx/sites-enabled/
          sudo systemctl restart nginx

          # ---- Persist FastAPI with systemd ----
          cat << 'EOF' | sudo tee /etc/systemd/system/meetingpolice-backend.service
          [Unit]
          Description=MeetingPolice FastAPI backend
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/MeetingPolice/backend
          Environment="PATH=/home/ubuntu/MeetingPolice/venv/bin"
          ExecStart=/home/ubuntu/MeetingPolice/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl enable meetingpolice-backend
          sudo systemctl start meetingpolice-backend

          echo "MeetingPolice (t3.small) setup complete."
    Metadata:
      Comment: EC2 sets up HTTPS FastAPI + Nginx from GitHub (t3.small)

  MeetingPoliceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MeetingPoliceEC2
